{% set name = "spotipy2" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CyanBook/spotipy2/archive/v{{ version }}.tar.gz
  sha256: f230999c0a9ddceed8c69f30324e4d936faefe5c5145d79147b4b059caa6e50a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiohttp
    - python >={{ python_min }}

test:
  imports:
    - spotipy2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://spotipy2.org/
  summary: The next generation Spotify Web API wrapper for Python
  dev_url: https://github.com/CyanBook/spotipy2
  license: LGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - captivus
